#action.yml
name: "Update conan center index"
description: "Create a version bump update for the conan center index for a specific recipe"
inputs:
  version: # id of input
    description: "the version to push"
    required: true
  fork_of_index:
    description: "The repository containing the fork"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  build-args:
    FORK_OF_INDEX: ${{ input.fork_of_index }}
# todo update with upstream
# add to recipe
