#action.yml
name: "Update conan center index"
description: "Create a version bump update for the conan center index for a specific recipe"
inputs:
  version: # id of input
    description: "the version to push"
    required: true
  fork-of-index:
    description: "The repository containing the fork"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.fork-of-index }}
        ref: "refs/heads/master"
# todo update with upstream
# add to recipe
